apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kyverno-notation-venafi.clusterRoleName" . }}binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kyverno-notation-venafi.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kyverno-notation-venafi.serviceAccountName" . }}
  namespace: {{ template "kyverno-notation-venafi.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kyverno-notation-venafi.clusterRoleName" . }}binding-venafi-token-review
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ template "kyverno-notation-venafi.serviceAccountName" . }}
  namespace: {{ template "kyverno-notation-venafi.namespace" . }}
