apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kyverno-notation-venafi.serviceAccountName" . }}
  namespace: {{ template "kyverno-notation-venafi.namespace" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
