apiVersion: notation.nirmata.io/v1alpha1
kind: TrustStore
metadata:
  name: venafi-signer-ts
spec:
  trustStoreName: example.com
  type: ca
  caBundle: |-
    -----BEGIN CERTIFICATE-----
    MIIDADCCAeigAwIBAgIRAKLCUshiFwdFkmFDL3bCBXEwDQYJKoZIhvcNAQELBQAw
    EjEQMA4GA1UEChMHbmlybWF0YTAeFw0yMzEwMTYxNjE0NTlaFw0yNDEwMTUxNjE0
    NTlaMBIxEDAOBgNVBAoTB25pcm1hdGEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQDFy7a7guzNyCNdshzZCbcwcR8EcbEqDwswqTDgiQFw7ah6YSakBXV/
    isMm8ZB0HVJS4OaxUrRw7xN+6hr4i6X+Hh07QPDMZ6Zcfs3DyYkB3l5hZKJQQlKK
    +7akOtK7Gq/V3Rfsmti/7U57XB/yvDnf49evQwNFHDzIVKvxnjVCVqXaMNDCgnb6
    9sgbEA1Qbt+sJ8dL8q6sK2NSSnCa+jkDsEFGY0OAUEWb6jhcsRwhQK89y8DKmtCq
    bNYko/JQv5eEpnEhHHDTSqhuz/qT9MBOM4OYnrpzNxhkCq5APobYtkPr1y4Q3ihK
    GsncN/i0fvdIxNIi+laLCOJF/imP4Cc7AgMBAAGjUTBPMB0GA1UdDgQWBBR+39jN
    ih6KgmEz9N5WHhON86zwjjAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIGgDATBgNV
    HSUEDDAKBggrBgEFBQcDAzANBgkqhkiG9w0BAQsFAAOCAQEAfwJoLYY8iyRRSIDs
    C0jg41+f+3q24GSvbm4TxjVMy68GhN9vimWF0Lw5GW+8oM2Cujk1/khzzMR73PrM
    0/9UBxXCLsOUktppBXowxbQclnIswxhEaQmbhzfrwhPEC37CBsjd9tQnluLC3MjO
    me8Qb97G9uItS5vwwdSAX1+G107vYmgy/GVRY0DwQIs7qk7R7HekpoMKKjcHKgXM
    Uiq//sQmzjmsI1ydCwUeE0cGRnHy5JbJjeih2eHTMhpmf4NR0tJQpJHjUvJLo0zY
    HDCc1xoU96cMpYeZ5DhsuibZqVN36ZQCln53WIgKs+boCbufFIQNZFLqF2JJO5yy
    jTvLIw==
    -----END CERTIFICATE-----