apiVersion: notation.nirmata.io/v1alpha1
kind: TrustPolicy
metadata:
  name: venafi-trustpolicy-sample
spec:
  version: '1.0'
  trustPolicyName: tp-venafi-test-notation
  trustPolicies:
  - name: venafi-signer-tp
    registryScopes:
    - "*"
    signatureVerification:
      level: strict
      override: {}
    trustStores:
    - ca:example.com
    trustedIdentities:
    - "*"