apiVersion: notation.nirmata.io/v1alpha1
kind: TrustPolicy
metadata:
  name: trustpolicy-sample
spec:
  version: '1.0'
  trustPolicyName: tp-test-notation
  trustPolicies:
  - name: venafi-signer-tp
    registryScopes:
    - "*"
    signatureVerification:
      level: strict
      override: {}
    trustStores:
    - signingAuthority:venafi-signer-ts
    trustedIdentities:
    - "arn:venafi:signer:us-west-2:844333597536:/signing-profiles/kyvernodemo"
---
apiVersion: notation.nirmata.io/v1alpha1
kind: TrustPolicy
metadata:
  name: trustpolicy-sample-fail
spec:
  version: '1.0'
  trustPolicyName: tp-test-notation-fail
  trustPolicies:
  - name: venafi-signer-tp
    registryScopes:
    - "*"
    signatureVerification:
      level: strict
      override: {}
    trustStores:
    - signingAuthority:venafi-signer-ts-fail
    trustedIdentities:
    - "arn:venafi:signer:us-west-2:844333597536:/signing-profiles/kyvernodemo"